server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/s3-demo
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        instance-profile: false
        access-key: test
        secret-key: test
      s3:
        endpoint: http://localhost:4566
        bucketName: s3-demo-bucket
        path-style-access: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB