spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        instance-profile: false
        access-key: test
        secret-key: test
      s3:
        bucketName: s3-demo-bucket
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB